# storage / boot media
force_drivers+=" nvme pcieport usb_storage uas xhci_pci xhci_hcd scsi_mod sd_mod phy_qcom_qmp_pcie "
# keyboard / touch input
force_drivers+=" i2c_hid i2c_hid_of i2c_qcom_geni hid hid_generic usbhid "
# display / Type-C altmode
force_drivers+=" leds_qcom_lpg pwm_bl qrtr spmi_pmic_arb pmic_glink_altmode gpio_sbu_mux panel_edp msm "
force_drivers+=" phy_qcom_qmp_combo phy_qcom_edp "

for fw in \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/qcdxkmsuc8380.mbn \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/qcadsp8380.mbn \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/adsp_dtbs.elf \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/qccdsp8380.mbn \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/cdsp_dtbs.elf \
	/usr/lib/firmware/qcom/x1e80100/dell/inspiron-14-plus-7441/qcvss8380.mbn \
	/usr/lib/firmware/qcom/gen80100_sqe.fw \
	/usr/lib/firmware/qcom/gen80100_aqe.fw \
	/usr/lib/firmware/qcom/gen80100_gmu.bin \
	/usr/lib/firmware/qcom/x1e80100/gen70500_zap.mbn
	do
	for ext in .zst .xz ""; do
		if [ -e "${fw}${ext}" ]; then
			install_items+=" ${fw}${ext} "
			break
		fi
	done
done
